# Generated by Django 4.2.11 on 2024-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
