# Generated by Django 4.2.11 on 2024-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_otp_device"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["id", "email", "first_name"], name="accounts_us_id_3c32af_idx"
            ),
        ),
    ]
