# Generated by Django 4.2.11 on 2024-12-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deliveryaddress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
