# Generated by Django 4.2.11 on 2024-07-14 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_notification_link_notification_send_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
