# Generated by Django 4.2.11 on 2024-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_userdevice_signature_alter_userdevice_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteviewlog",
            name="city",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteviewlog",
            name="country",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteviewlog",
            name="enclg",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteviewlog",
            name="encsh",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteviewlog",
            name="region",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
