# Generated by Django 4.2.11 on 2024-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_siteviewlog_city_siteviewlog_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteviewlog",
            name="enclg",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="signature",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
