# Generated by Django 4.2.11 on 2024-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_user_is_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteviewlog",
            name="enclg",
            field=models.CharField(max_length=200),
        ),
    ]
