# Generated by Django 4.2.11 on 2024-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_siteviewlog_enclg"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
