# Generated by Django 4.2.11 on 2024-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_user_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social",
            field=models.CharField(
                blank=True, default="default", max_length=255, null=True
            ),
        ),
    ]
