# Generated by Django 4.2.11 on 2024-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_user_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
