# Generated by Django 4.2.11 on 2024-08-01 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
