# Generated by Django 4.2.11 on 2024-08-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='layout_slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layout',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
