# Generated by Django 4.2.11 on 2024-08-31 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_title_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='layout_section',
        ),
        migrations.AddField(
            model_name='image',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='layout.layout'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LayoutSection',
        ),
    ]
