# Generated by Django 4.2.11 on 2024-09-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_remove_image_layout_section_image_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='no_image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
