# Generated by Django 4.2.11 on 2024-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_layout_no_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
