# Generated by Django 4.2.11 on 2024-06-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.BooleanField(blank=True, null=True)),
                ('minimum', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('maxamt', models.IntegerField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, null=True)),
                ('valid', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionuid', models.IntegerField(blank=True, null=True)),
                ('sub_total', models.FloatField()),
                ('shipping', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('total_amt', models.FloatField()),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('redeem_amt', models.FloatField(blank=True, null=True)),
                ('grand_total', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('costumer_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('redeemCode', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sales.redeem_code')),
            ],
        ),
        migrations.CreateModel(
            name='Saled_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('total', models.FloatField()),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Add_to_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('costumer_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cart_costumer_name', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
