# Generated by Django 4.2.11 on 2024-07-29 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Add_to_Cart",
        ),
    ]
