# Generated by Django 4.2.11 on 2024-09-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_addtocart_unique_together'),
        ('sales', '0002_delete_add_to_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeem_code',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='redeem_code',
            old_name='valid',
            new_name='valid_until',
        ),
        migrations.RemoveField(
            model_name='redeem_code',
            name='maxamt',
        ),
        migrations.AddField(
            model_name='saled_products',
            name='variant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='redeem_code',
            name='type',
            field=models.CharField(blank=True, choices=[('amount', 'Amount'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('proceed', 'Proceed'), ('packed', 'Packed'), ('delivered', 'Delivered'), ('successful', 'Successful')], default='pending', max_length=10),
        ),
    ]
