# Generated by Django 4.2.11 on 2024-11-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_transactionuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saled_products',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='redeemCode',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='redeem_amt',
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='redeem_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
