# Generated by Django 4.2.11 on 2024-11-30 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deliveryaddress_unique_together_and_more'),
        ('sales', '0003_remove_saled_products_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='shipping',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.deliveryaddress'),
        ),
    ]
