# Generated by Django 4.2.11 on 2024-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeem_code',
            name='used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
