# Generated by Django 4.2.11 on 2024-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name_alter_productimage_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product_stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
