# Generated by Django 4.2.11 on 2024-11-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_discount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_id_5eaa13_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'product_name', 'productslug'], name='products_pr_id_f42bd0_idx'),
        ),
    ]
