# Generated by Django 4.2.11 on 2024-12-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_pr_id_5eaa13_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='favoutare',
            field=models.BooleanField(default=False),
        ),
    ]
