# Generated by Django 4.2.11 on 2024-07-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_product_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='variant',
            new_name='product',
        ),
    ]
