# Generated by Django 4.2.11 on 2024-07-29 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0008_addtocart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addtocart",
            name="costumer_name",
        ),
        migrations.RemoveField(
            model_name="addtocart",
            name="qty",
        ),
        migrations.AddField(
            model_name="addtocart",
            name="variant",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="cart_product_variant",
                to="products.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="addtocart",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_product",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="addtocart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
