# Generated by Django 4.2.11 on 2024-08-06 17:03

from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_addtocart_costumer_name_remove_addtocart_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[products.utils.validate_image_format]),
        ),
    ]
