# Generated by Django 4.2.11 on 2024-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='pcs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
