# Generated by Django 4.2.11 on 2024-09-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_addtocart_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
    ]
