# Generated by Django 4.2.11 on 2024-09-25 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_review_delivery_review_recommended'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addtocart',
            unique_together={('user', 'variant')},
        ),
    ]
